apiVersion: v1
kind: Service
metadata:
  name: api-product-service
spec:
  selector:
    app: api-product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer